language: csharp
mono: none
dotnet: 2.0.0
solution: Emby.AutoOrganize.sln
install:
- dotnet restore
script:
- dotnet build -c Release
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: releases
  api_key:
    secure: q3QLuwWTSbVxUvuuUz4qYj2DPqYAn563skybARpptMOx/IWu5wuLIr29XrBYyH0T5B6KSN9Lfa3FnZT4CSG6TvAYXW+JH3AwyNg0eQdlaY/MQ1GCbIMVyZn8vpo/dU5S2+QUZ/ewEyDCJgAHA5WeX7CIKlOSpCWM3brgrcUD5XXmubCDKfc6QCBSI3Vi//ZevZyeMxE3HzQnF26Hanf0tE4X71bAneYXXKi550gFNMOIp0voXB29AXFTCLz3XcENHIUAOPOi7CKmju4vTaIuuv5fmigTlZkS0ZSnbQLpkCyT7uts165GQehjHP7jZUw1lTQxwExcPguLL1BCtnwT0Xr7ZiaZzywe/XKKHPobKGjhBPfZr9UytwCDTSYmq7IkvVD/xkoJuJFygRzgSC1ktc7xnsl8gNYEIHCte/H7X3iO2WPE8SOVeDm8Esj4Gem4goFKMGGji249MAuyiQoOhUw7Lv9BRGyW18OAGg9Qf/wk2Q0rmA18vTEuFmOt0jyUmyD0aFcxT8zWZ42X/rcn2J1ZGUemfQHPERo9a/3JAyn0mujFQyEs3nfIGRzDNZ9JY5mSaOj16k0aVIKQVgldr1yDMcgFArG2XzPx8UCchRXIaOHf7BALIxS5y3rPxtFGPfxIGSaBEySV8F1PlTgqK0Rxi9hzDJVilmdJZVpX/9o=
  file: Emby.AutoOrganize/bin/Release/netstandard2.0/Emby.AutoOrganize.dll
  skip_cleanup: true
  on:
    repo: PoppyPop/Emby.AutoOrganize
    tags: true
